export interface houseCardProps{
   id:number,
   title:string,
   address:string,
   photos:string,
   rate:string,
   discounted_price:string,
   price:string,
   tags:string,
   last_updated:string,
   capacity:number,
   location:string
   categories:string,
   bathrooms:number,
   parking:number,
   room:number,
   yard_type:null,
   num_comments:number,
   discount_id:null,
   transaction_type:"mortgage" | "rental" | "reservation" | "direct purchase",
   sellerId:number,
   sellerName:string,
   caption:string,
   bookings:number,
   favoriteId:null,
   isFavorite:boolean

}

export interface houseCardReserveProps{
   id:number,
   title:string,
   address:string,
   photos:string[],
   rate:number,
   discounted_price:number,
   price:number,
   tags:string,
   last_updated:string,
   capacity:number,
   location:string
   categories:string,
   bathrooms:number,
   parking:number,
   room:number,
   yard_type:null,
   num_comments:number,
   discount_id:null,
   transaction_type:"mortgage" | "rental" | "reservation" | "direct purchase",
   sellerId:number,
   sellerName:string,
   caption:string,
   bookings:number,
   favoriteId:null,
   isFavorite:boolean,
   checkInDate:string,
   checkOutDate:string

}

// "id": 6,
//       "title": "اپارتمان مدرن ایتالیایی",
//       "address": "ساری سلمان فارسی",
//       "photos": null,
//       "rate": "3",
//       "discounted_price": "2500000",
//       "price": "3000000",
//       "tags": "apartment",
//       "last_updated": "2026-05-10T18:47:27.000Z",
//       "capacity": 4,
//       "location": "ساری . سلمان فارسی",
//       "categories": null,
//       "bathrooms": 4,
//       "parking": 4,
//       "rooms": 4,
//       "yard_type": null,
//       "num_comments": 0,
//       "discount_id": null,
//       "transaction_type": "mortgage",
//       "sellerId": 175,
//       "sellerName": "ادمین اکانت",
//       "caption": "اپارتمان مدرن ایتالیایی واقع در سلمان فارسی با ویوی عالی و امکانات فوق العاده",
//       "bookings": 0,
//       "favoriteId": null,
//       "isFavorite": false