import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./components/common/Header/Header";
import FooterComponent from "./components/common/Footer/Footer";
// import localFont from 'next/font/local';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// const dirooz = localFont({
//   src:"./assets/fonts/dirooz-font-v0.2.1/Dirooz.woff",
//   variable: "--font-dirooz"
// })


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col gap-5 ">
        <header className="w-full px-16 py-6">
          <HeaderComponent />
        </header>
        {children}
        <footer className="w-full px-16 py-6">
          <FooterComponent />
          </footer></body>
    </html>
  );
}
